#' exclusion_criteria
#'
#' \lifecycle{experimental}
#'
#' @description Exclusion criteria
#' @param data a data object generated by the \code{multics::chop_css} function
#' @param cutoff cut off score. Default to 0.01
#' @details Here the different exclusion criteria are applied to the provided data.
#' @export

exclusion_criteria <- function(data, cutoff = 0.01) {
  # Check data
  chop_css_warning(data)

  last_trial <- data %>% dplyr::filter(cs_ltrial > cutoff)
  last2_trial <- data %>% dplyr::filter(l1trial > cutoff & l2trial > cutoff)
  last_first_trial <- data %>% dplyr::filter(cs_lftdiff > cutoff)
  half_trials <- data %>% dplyr::mutate(difftr = cs_lhalf - cs_fhalf) %>% dplyr::filter(difftr > cutoff)

 res <- tidyr::tibble(
    used_data = list(
    full_data = data,
    last_trial = last_trial,
    last2_trial = last2_trial,
    last_first_trial = last_first_trial,
    half_trials = half_trials
  ))

 res <- res %>%
   dplyr::mutate(names = names(.$used_data),
                 cutoff = cutoff,
                 nam_cut = paste(names, ", cutoff =", cutoff))

  return(res)
}
