.onLoad <- function (libname, pkgname) {
  # set global variables in order to avoid CHECK notes
  utils::globalVariables (".")
  utils::globalVariables ("..density..")
  utils::globalVariables ("all_of")
  utils::globalVariables ("alternative")
  utils::globalVariables ("base_model_tab")
  utils::globalVariables ("base_model_time_tab")
  utils::globalVariables ("base_model_time_rand_tab")
  utils::globalVariables ("BIC")
  utils::globalVariables ("BF")
  utils::globalVariables ("cs")
  utils::globalVariables ("CS")
  utils::globalVariables ("cs1")
  utils::globalVariables ("cs2")
  utils::globalVariables ("cs_fhalf")
  utils::globalVariables ("cs_lftdiff")
  utils::globalVariables ("cs_lhalf")
  utils::globalVariables ("cs_ltrial")
  utils::globalVariables ("cs1_mean")
  utils::globalVariables ("cs2_mean")
  utils::globalVariables ("conf.high")
  utils::globalVariables ("conf.low")
  utils::globalVariables ("controls")
  utils::globalVariables ("cs_model_tab")
  utils::globalVariables ("cs_model_time_rand_tab")
  utils::globalVariables ("difftr")
  utils::globalVariables ("effect.size")
  utils::globalVariables ("estimate")
  utils::globalVariables ("excl")
  utils::globalVariables ("group")
  utils::globalVariables ("group2")
  utils::globalVariables ("id")
  utils::globalVariables ("l1trial")
  utils::globalVariables ("l2trial")
  utils::globalVariables ("method")
  utils::globalVariables ("model")
  utils::globalVariables ("models")
  utils::globalVariables ("omegasq")
  utils::globalVariables ("p.value")
  utils::globalVariables ("res")
  utils::globalVariables ("resp")
  utils::globalVariables ("repeated measures ANOVA with time")
  utils::globalVariables ("repeated measures ANOVA without time")
  utils::globalVariables ("rowname")
  utils::globalVariables ("statistic")
  utils::globalVariables ("stratum")
  utils::globalVariables ("t.value")
  utils::globalVariables ("term")
  utils::globalVariables ("time")
  utils::globalVariables ("time_cs_model_time_tab")
  utils::globalVariables ("Value")
  utils::globalVariables ("value")
  utils::globalVariables ("var_old")
  utils::globalVariables ("x")
  utils::globalVariables ("y")
  invisible ()
}
